#! /bin/sh
# /etc/init.d/teamcity
#
# script for centos service to start team city and its build agent

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script teamcity "
    sudo -u teamcity /var/TeamCity/bin/runAll.sh start
    ;;
  stop)
    echo "Stopping script teamcity"
    sudo -u teamcity /var/TeamCity/bin/runAll.sh stop
    ;;
  *)
    echo "Usage: /etc/init.d/teamcity {start|stop}"
    exit 1
    ;;
esac

exit 0
